import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Header
    'header.back': 'Volver',
    'header.title': 'Historia de Chile',
    'header.takeQuiz': 'Hacer Quiz',

    // Main
    'main.title': 'Descubre la Historia de Chile',
    'main.subtitle': 'Explora los eventos, personajes y momentos clave que dieron forma a la nación chilena desde tiempos precolombinos hasta la actualidad.',
    'main.testKnowledge': 'Pon a Prueba tus Conocimientos',

    // Tabs
    'tabs.history': 'Historia',
    'tabs.culture': 'Cultura',

    // Sections
    'sections.keyEvents': 'Eventos Clave',
    'sections.keyFigures': 'Figuras Importantes',

    // Quiz
    'quiz.title': 'Quiz de Historia de Chile',
    'quiz.home': 'Inicio',
    'quiz.questionNumber': 'Pregunta',
    'quiz.of': 'de',
    'quiz.difficulty': 'Dificultad',
    'quiz.easy': 'Fácil',
    'quiz.medium': 'Medio',
    'quiz.hard': 'Difícil',
    'quiz.previous': 'Anterior',
    'quiz.showAnswer': 'Mostrar Respuesta',
    'quiz.results': 'Resultados',
    'quiz.completed': '¡Quiz Completado!',
    'quiz.scored': 'Obtuviste',
    'quiz.outOf': 'de',
    'quiz.questions': 'preguntas',
    'quiz.timeSpent': 'Tiempo',
    'quiz.grade': 'Calificación',
    'quiz.excellent': '¡Excelente!',
    'quiz.goodJob': '¡Buen Trabajo!',
    'quiz.notBad': 'No Está Mal',
    'quiz.keepStudying': 'Sigue Estudiando',
    'quiz.retryQuiz': 'Reintentar Quiz',
    'quiz.reviewMistakes': 'Revisar Errores',
    'quiz.nextQuestion': 'Siguiente Pregunta',
    'quiz.finishQuiz': 'Finalizar Quiz',

    // Auth
    'auth.welcomeBack': 'Bienvenido de Vuelta',
    'auth.createAccount': 'Crear Cuenta',
    'auth.signInDescription': 'Inicia sesión en tu cuenta para continuar aprendiendo historia chilena',
    'auth.signUpDescription': 'Únete a Chilenizate para seguir tu progreso y guardar tus resultados',
    'auth.fullName': 'Nombre Completo',
    'auth.enterFullName': 'Ingresa tu nombre completo',
    'auth.email': 'Correo Electrónico',
    'auth.enterEmail': 'Ingresa tu correo electrónico',
    'auth.password': 'Contraseña',
    'auth.enterPassword': 'Ingresa tu contraseña',
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.pleaseWait': 'Por favor espera...',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.haveAccount': '¿Ya tienes una cuenta?',
    'auth.home': 'Inicio',

    // Error Bin
    'errorBin.title': 'Bin de Errores',
    'errorBin.noErrors': '¡Sin Errores Aún!',
    'errorBin.emptyDescription': 'Tu bin de errores está vacío. Toma el quiz para ver las preguntas que respondiste mal aquí para repasar.',
    'errorBin.takeQuiz': 'Hacer Quiz',
    'errorBin.yourErrorBin': 'Tu Bin de Errores',
    'errorBin.reviewPractice': 'Repasa y practica',
    'errorBin.questionsWrong': 'pregunta(s) que respondiste mal',
    'errorBin.practiceAll': 'Practicar Todas las Preguntas',
    'errorBin.clearAll': 'Limpiar Todo',
    'errorBin.practiceMode': 'Modo Práctica',
    'errorBin.exitPractice': 'Salir de Práctica',
    'errorBin.practiceComplete': 'Práctica Completa',
    'errorBin.greatJob': '¡Excelente Trabajo!',
    'errorBin.completedSession': 'Has completado tu sesión de práctica del bin de errores.',
    'errorBin.returnToBin': 'Volver al Bin de Errores',
    'errorBin.takeFullQuiz': 'Hacer Quiz Completo Otra Vez',
    'errorBin.previouslyIncorrect': 'Esta pregunta fue respondida incorrectamente anteriormente. Responde correctamente para quitarla de tu bin de errores.',
    'errorBin.explanation': 'Explicación:',
    'errorBin.loading': 'Cargando preguntas de errores...',

    // Quiz Questions - Historical
    'quiz.q1.question': '¿Quién fundó la ciudad de Santiago en 1541?',
    'quiz.q1.opt1': 'Pedro de Valdivia',
    'quiz.q1.opt2': 'Diego de Almagro',
    'quiz.q1.opt3': 'Francisco Pizarro',
    'quiz.q1.opt4': 'Hernán Cortés',
    'quiz.q1.explanation': 'Pedro de Valdivia fundó Santiago de la Nueva Extremadura el 12 de febrero de 1541.',

    'quiz.q2.question': '¿En qué año Chile declaró su independencia?',
    'quiz.q2.opt1': '1810',
    'quiz.q2.opt2': '1818',
    'quiz.q2.opt3': '1817',
    'quiz.q2.opt4': '1820',
    'quiz.q2.explanation': 'Chile declaró formalmente su independencia en 1818, aunque el proceso comenzó en 1810.',

    'quiz.q3.question': '¿Cuál fue la batalla decisiva para la independencia de Chile?',
    'quiz.q3.opt1': 'Batalla de Rancagua',
    'quiz.q3.opt2': 'Batalla de Maipú',
    'quiz.q3.opt3': 'Batalla de Chacabuco',
    'quiz.q3.opt4': 'Batalla de Cancha Rayada',
    'quiz.q3.explanation': 'La Batalla de Chacabuco (1817) fue decisiva para asegurar la independencia de Chile.',

    'quiz.q4.question': '¿Quién fue el primer presidente de Chile?',
    'quiz.q4.opt1': 'José Miguel Carrera',
    'quiz.q4.opt2': 'Bernardo O\'Higgins',
    'quiz.q4.opt3': 'Manuel Blanco Encalada',
    'quiz.q4.opt4': 'Ramón Freire',
    'quiz.q4.explanation': 'Bernardo O\'Higgins fue el primer Director Supremo (equivalente a presidente) de Chile.',

    'quiz.q5.question': '¿Qué guerra expandió significativamente el territorio chileno?',
    'quiz.q5.opt1': 'Guerra de la Confederación',
    'quiz.q5.opt2': 'Guerra del Pacífico',
    'quiz.q5.opt3': 'Guerra de Arauco',
    'quiz.q5.opt4': 'Guerra Civil de 1891',
    'quiz.q5.explanation': 'La Guerra del Pacífico (1879-1884) permitió a Chile ganar territorio en el norte.',

    'quiz.q6.question': '¿Cuál era el principal producto de exportación durante el siglo XIX?',
    'quiz.q6.opt1': 'Cobre',
    'quiz.q6.opt2': 'Salitre',
    'quiz.q6.opt3': 'Plata',
    'quiz.q6.opt4': 'Trigo',
    'quiz.q6.explanation': 'El salitre fue el principal producto de exportación que trajo gran riqueza a Chile.',

    'quiz.q7.question': '¿Quién fue el líder mapuche más famoso en la resistencia española?',
    'quiz.q7.opt1': 'Caupolicán',
    'quiz.q7.opt2': 'Lautaro',
    'quiz.q7.opt3': 'Galvarino',
    'quiz.q7.opt4': 'Janequeo',
    'quiz.q7.explanation': 'Lautaro fue uno de los líderes mapuches más destacados en la Guerra de Arauco.',

    'quiz.q8.question': '¿En qué año se promulgó la actual Constitución de Chile?',
    'quiz.q8.opt1': '1925',
    'quiz.q8.opt2': '1980',
    'quiz.q8.opt3': '1990',
    'quiz.q8.opt4': '2005',
    'quiz.q8.explanation': 'La Constitución actual fue promulgada en 1980 durante el gobierno militar.',

    'quiz.q9.question': '¿Cuál fue el primer partido político de Chile?',
    'quiz.q9.opt1': 'Partido Liberal',
    'quiz.q9.opt2': 'Partido Conservador',
    'quiz.q9.opt3': 'Partido Radical',
    'quiz.q9.opt4': 'Partido Nacional',
    'quiz.q9.explanation': 'El Partido Liberal fue uno de los primeros partidos políticos formales de Chile.',

    'quiz.q10.question': '¿Quién fue presidente durante la Gran Depresión en Chile?',
    'quiz.q10.opt1': 'Arturo Alessandri',
    'quiz.q10.opt2': 'Carlos Ibáñez del Campo',
    'quiz.q10.opt3': 'Juan Esteban Montero',
    'quiz.q10.opt4': 'Pedro Aguirre Cerda',
    'quiz.q10.explanation': 'Carlos Ibáñez del Campo gobernó durante parte de la Gran Depresión.',

    'quiz.q11.question': '¿Cuándo terminó oficialmente la Guerra de Arauco?',
    'quiz.q11.opt1': '1641',
    'quiz.q11.opt2': '1881',
    'quiz.q11.opt3': '1598',
    'quiz.q11.opt4': '1723',
    'quiz.q11.explanation': 'La Guerra de Arauco terminó oficialmente en 1881 con la pacificación de la Araucanía.',

    'quiz.q12.question': '¿Quién fue el último presidente antes del golpe de 1973?',
    'quiz.q12.opt1': 'Eduardo Frei Montalva',
    'quiz.q12.opt2': 'Salvador Allende',
    'quiz.q12.opt3': 'Jorge Alessandri',
    'quiz.q12.opt4': 'Gabriel González Videla',
    'quiz.q12.explanation': 'Salvador Allende fue derrocado en el golpe militar del 11 de septiembre de 1973.',

    'quiz.q13.question': '¿Qué presidente implementó la reforma agraria más significativa?',
    'quiz.q13.opt1': 'Jorge Alessandri',
    'quiz.q13.opt2': 'Eduardo Frei Montalva',
    'quiz.q13.opt3': 'Salvador Allende',
    'quiz.q13.opt4': 'Carlos Ibáñez del Campo',
    'quiz.q13.explanation': 'Eduardo Frei Montalva implementó una reforma agraria significativa en los años 60.',

    'quiz.q14.question': '¿Cuál fue el primer nombre de Santiago?',
    'quiz.q14.opt1': 'Santiago del Nuevo Extremo',
    'quiz.q14.opt2': 'Santiago de la Nueva Extremadura',
    'quiz.q14.opt3': 'Santiago de Chile',
    'quiz.q14.opt4': 'Santiago de Compostela',
    'quiz.q14.explanation': 'Santiago fue originalmente fundada como Santiago de la Nueva Extremadura.',

    'quiz.q15.question': '¿Quién lideró el cruce de los Andes junto con San Martín?',
    'quiz.q15.opt1': 'Bernardo O\'Higgins',
    'quiz.q15.opt2': 'José Miguel Carrera',
    'quiz.q15.opt3': 'Manuel Rodríguez',
    'quiz.q15.opt4': 'Ramón Freire',
    'quiz.q15.explanation': 'Bernardo O\'Higgins colaboró estrechamente con San Martín en el cruce de los Andes.',

    'quiz.q16.question': '¿En qué siglo llegaron los primeros inmigrantes alemanes a Chile?',
    'quiz.q16.opt1': 'Siglo XVII',
    'quiz.q16.opt2': 'Siglo XIX',
    'quiz.q16.opt3': 'Siglo XVIII',
    'quiz.q16.opt4': 'Siglo XX',
    'quiz.q16.explanation': 'Los primeros inmigrantes alemanes llegaron a Chile en el siglo XIX.',

    'quiz.q17.question': '¿Cuál fue la primera universidad de Chile?',
    'quiz.q17.opt1': 'Universidad de Chile',
    'quiz.q17.opt2': 'Universidad Católica',
    'quiz.q17.opt3': 'Universidad de Concepción',
    'quiz.q17.opt4': 'Universidad de Valparaíso',
    'quiz.q17.explanation': 'La Universidad de Chile fue la primera universidad del país, fundada en 1842.',

    'quiz.q18.question': '¿Qué conquistador español exploró por primera vez territorio chileno?',
    'quiz.q18.opt1': 'Diego de Almagro',
    'quiz.q18.opt2': 'Pedro de Valdivia',
    'quiz.q18.opt3': 'Francisco Pizarro',
    'quiz.q18.opt4': 'Vasco Núñez de Balboa',
    'quiz.q18.explanation': 'Diego de Almagro fue el primer español en explorar territorio chileno en 1536.',

    'quiz.q19.question': '¿Cuántos años duró el gobierno militar en Chile?',
    'quiz.q19.opt1': '15 años',
    'quiz.q19.opt2': '16 años',
    'quiz.q19.opt3': '18 años',
    'quiz.q19.opt4': '17 años',
    'quiz.q19.explanation': 'El gobierno militar duró 17 años, desde 1973 hasta 1990.',

    'quiz.q20.question': '¿Quién fue el primer presidente después del retorno a la democracia?',
    'quiz.q20.opt1': 'Eduardo Frei Ruiz-Tagle',
    'quiz.q20.opt2': 'Patricio Aylwin',
    'quiz.q20.opt3': 'Ricardo Lagos',
    'quiz.q20.opt4': 'Michelle Bachelet',
    'quiz.q20.explanation': 'Patricio Aylwin fue el primer presidente democrático tras el gobierno militar.',

    'quiz.q21.question': '¿En qué región se encuentra el desierto de Atacama?',
    'quiz.q21.opt1': 'Tarapacá',
    'quiz.q21.opt2': 'Antofagasta',
    'quiz.q21.opt3': 'Atacama',
    'quiz.q21.opt4': 'Todas las anteriores',
    'quiz.q21.explanation': 'El desierto de Atacama se extiende por varias regiones del norte de Chile.',

    'quiz.q22.question': '¿Cuál es el volcán más alto de Chile?',
    'quiz.q22.opt1': 'Volcán Osorno',
    'quiz.q22.opt2': 'Ojos del Salado',
    'quiz.q22.opt3': 'Volcán Villarrica',
    'quiz.q22.opt4': 'Volcán Llaima',
    'quiz.q22.explanation': 'Ojos del Salado es el volcán más alto de Chile y del mundo.',

    'quiz.q23.question': '¿Cuál fue la primera capital de Chile?',
    'quiz.q23.opt1': 'Valparaíso',
    'quiz.q23.opt2': 'La Serena',
    'quiz.q23.opt3': 'Santiago',
    'quiz.q23.opt4': 'Concepción',
    'quiz.q23.explanation': 'Santiago ha sido la capital de Chile desde su fundación en 1541.',

    'quiz.q24.question': '¿Qué presidente chileno recibió el Premio Nobel de Literatura?',
    'quiz.q24.opt1': 'Gabriel González Videla',
    'quiz.q24.opt2': 'Ninguno fue presidente',
    'quiz.q24.opt3': 'Salvador Allende',
    'quiz.q24.opt4': 'Eduardo Frei Montalva',
    'quiz.q24.explanation': 'Ningún presidente chileno ha recibido el Premio Nobel de Literatura.',

    'quiz.q25.question': '¿Cuál es el río más largo de Chile?',
    'quiz.q25.opt1': 'Río Maipo',
    'quiz.q25.opt2': 'Río Loa',
    'quiz.q25.opt3': 'Río Bío Bío',
    'quiz.q25.opt4': 'Río Baker',
    'quiz.q25.explanation': 'El río Loa es el más largo de Chile con 440 kilómetros.',

    'quiz.q26.question': '¿Cuándo se fundó Valparaíso?',
    'quiz.q26.opt1': '1541',
    'quiz.q26.opt2': '1544',
    'quiz.q26.opt3': '1536',
    'quiz.q26.opt4': '1550',
    'quiz.q26.explanation': 'Valparaíso fue fundada en 1544 por Juan de Saavedra.',

    'quiz.q27.question': '¿Qué etnia indígena habitaba principalmente el norte de Chile?',
    'quiz.q27.opt1': 'Mapuches',
    'quiz.q27.opt2': 'Atacameños',
    'quiz.q27.opt3': 'Tehuelches',
    'quiz.q27.opt4': 'Onas',
    'quiz.q27.explanation': 'Los atacameños habitaban principalmente el norte de Chile.',

    'quiz.q28.question': '¿Cuál fue la moneda chilena antes del peso actual?',
    'quiz.q28.opt1': 'Real',
    'quiz.q28.opt2': 'Escudo',
    'quiz.q28.opt3': 'Sol',
    'quiz.q28.opt4': 'Condor',
    'quiz.q28.explanation': 'El escudo fue la moneda chilena entre 1960 y 1975.',

    'quiz.q29.question': '¿Quién escribió "La Araucana"?',
    'quiz.q29.opt1': 'Pedro de Oña',
    'quiz.q29.opt2': 'Alonso de Ercilla',
    'quiz.q29.opt3': 'Francisco Núñez de Pineda',
    'quiz.q29.opt4': 'Diego de Rosales',
    'quiz.q29.explanation': 'Alonso de Ercilla escribió el poema épico "La Araucana".',

    'quiz.q30.question': '¿En qué año Chile se convirtió en miembro de la ONU?',
    'quiz.q30.opt1': '1945',
    'quiz.q30.opt2': '1946',
    'quiz.q30.opt3': '1947',
    'quiz.q30.opt4': '1948',
    'quiz.q30.explanation': 'Chile fue uno de los miembros fundadores de la ONU en 1945.',

    // New Cultural Questions (31-35)
    'quiz.q31.question': '¿Cuál es el significado de "Bacán" en el chileno?',
    'quiz.q31.opt1': 'Genial, increíble',
    'quiz.q31.opt2': 'Aburrido',
    'quiz.q31.opt3': 'Difícil',
    'quiz.q31.opt4': 'Caro',
    'quiz.q31.explanation': '"Bacán" se usa para expresar que algo es genial o increíble.',

    'quiz.q32.question': '¿Qué representa la danza de la Cueca?',
    'quiz.q32.opt1': 'Una batalla',
    'quiz.q32.opt2': 'Una cosecha',
    'quiz.q32.opt3': 'El cortejo entre gallo y gallina',
    'quiz.q32.opt4': 'Un funeral',
    'quiz.q32.explanation': 'La Cueca representa el cortejo amoroso entre un gallo y una gallina.',

    'quiz.q33.question': '¿Qué significa "Al tiro" en Chile?',
    'quiz.q33.opt1': 'Despacio',
    'quiz.q33.opt2': 'De inmediato',
    'quiz.q33.opt3': 'Nunca',
    'quiz.q33.opt4': 'Tal vez',
    'quiz.q33.explanation': '"Al tiro" significa inmediatamente o ahora mismo.',

    'quiz.q34.question': '¿Quién es La Pincoya en la mitología chilota?',
    'quiz.q34.opt1': 'Una sirena que trae fortuna a los pescadores',
    'quiz.q34.opt2': 'Un fantasma malévolo',
    'quiz.q34.opt3': 'Una bruja del bosque',
    'quiz.q34.opt4': 'Un espíritu del viento',
    'quiz.q34.explanation': 'La Pincoya es una sirena mítica que trae buena fortuna a los pescadores.',

    'quiz.q35.question': '¿Qué comida es esencial durante las Fiestas Patrias?',
    'quiz.q35.opt1': 'Asado',
    'quiz.q35.opt2': 'Cazuela',
    'quiz.q35.opt3': 'Empanadas',
    'quiz.q35.opt4': 'Pastel de choclo',
    'quiz.q35.explanation': 'Las empanadas son la comida tradicional esencial durante las Fiestas Patrias.',

    // Geography Questions (36-40)
    'quiz.q36.question': '¿Cuál es la región más austral de Chile?',
    'quiz.q36.opt1': 'Los Lagos',
    'quiz.q36.opt2': 'Magallanes y Antártica Chilena',
    'quiz.q36.opt3': 'Aysén',
    'quiz.q36.opt4': 'Los Ríos',
    'quiz.q36.explanation': 'Magallanes y Antártica Chilena es la región más austral de Chile.',

    'quiz.q37.question': '¿Cuál es el desierto más árido del mundo ubicado en Chile?',
    'quiz.q37.opt1': 'Desierto de Atacama',
    'quiz.q37.opt2': 'Desierto de Sahara',
    'quiz.q37.opt3': 'Desierto de Gobi',
    'quiz.q37.opt4': 'Desierto de Kalahari',
    'quiz.q37.explanation': 'El desierto de Atacama es considerado el más árido del mundo.',

    'quiz.q38.question': '¿Cuáles son las islas más famosas pertenecientes a Chile?',
    'quiz.q38.opt1': 'Islas Galápagos',
    'quiz.q38.opt2': 'Islas Malvinas',
    'quiz.q38.opt3': 'Islas Juan Fernández',
    'quiz.q38.opt4': 'Isla de Pascua (Rapa Nui)',
    'quiz.q38.explanation': 'La Isla de Pascua es la más famosa de las islas chilenas por sus moais.',

    'quiz.q39.question': '¿Cuántas regiones tiene Chile actualmente?',
    'quiz.q39.opt1': '15',
    'quiz.q39.opt2': '16',
    'quiz.q39.opt3': '14',
    'quiz.q39.opt4': '17',
    'quiz.q39.explanation': 'Chile tiene actualmente 16 regiones.',

    'quiz.q40.question': '¿Cuál es la capital de la región de Valparaíso?',
    'quiz.q40.opt1': 'Viña del Mar',
    'quiz.q40.opt2': 'San Antonio',
    'quiz.q40.opt3': 'Valparaíso',
    'quiz.q40.opt4': 'Quillota',
    'quiz.q40.explanation': 'Valparaíso es la capital de la región de Valparaíso.',

    // Natural Resources Questions (41-43)
    'quiz.q41.question': '¿En qué posición mundial está Chile en producción de cobre?',
    'quiz.q41.opt1': 'Primera',
    'quiz.q41.opt2': 'Segunda',
    'quiz.q41.opt3': 'Tercera',
    'quiz.q41.opt4': 'Cuarta',
    'quiz.q41.explanation': 'Chile es el mayor productor mundial de cobre.',

    'quiz.q42.question': '¿Dónde se encuentran las mayores reservas de litio de Chile?',
    'quiz.q42.opt1': 'Desierto de Atacama',
    'quiz.q42.opt2': 'Salar de Atacama',
    'quiz.q42.opt3': 'Cordillera de los Andes',
    'quiz.q42.opt4': 'Valle Central',
    'quiz.q42.explanation': 'El Salar de Atacama contiene las mayores reservas de litio de Chile.',

    'quiz.q43.question': '¿Cuál es una de las industrias vitivinícolas más reconocidas internacionalmente?',
    'quiz.q43.opt1': 'Valle del Maipo',
    'quiz.q43.opt2': 'Valle del Elqui',
    'quiz.q43.opt3': 'Valle de Colchagua',
    'quiz.q43.opt4': 'Todas las anteriores',
    'quiz.q43.explanation': 'Todos estos valles son reconocidos mundialmente por su producción vitivinícola.',

    // National Symbols Questions (44-47)
    'quiz.q44.question': '¿Cuál es el animal nacional de Chile?',
    'quiz.q44.opt1': 'Huemul',
    'quiz.q44.opt2': 'Cóndor',
    'quiz.q44.opt3': 'Chinchilla',
    'quiz.q44.opt4': 'Vicuña',
    'quiz.q44.explanation': 'El huemul es el animal nacional de Chile y aparece en el escudo nacional.',

    'quiz.q45.question': '¿Cuál es el ave nacional de Chile?',
    'quiz.q45.opt1': 'Huemul',
    'quiz.q45.opt2': 'Cóndor',
    'quiz.q45.opt3': 'Flamenco',
    'quiz.q45.opt4': 'Águila',
    'quiz.q45.explanation': 'El cóndor andino es el ave nacional de Chile.',

    'quiz.q46.question': '¿Cuál es la flor nacional de Chile?',
    'quiz.q46.opt1': 'Rosa',
    'quiz.q46.opt2': 'Clavel',
    'quiz.q46.opt3': 'Copihue',
    'quiz.q46.opt4': 'Azucena',
    'quiz.q46.explanation': 'El copihue es la flor nacional de Chile.',

    'quiz.q47.question': '¿Qué árbol longevo puede vivir más de 3,000 años en Chile?',
    'quiz.q47.opt1': 'Araucaria',
    'quiz.q47.opt2': 'Alerce',
    'quiz.q47.opt3': 'Roble',
    'quiz.q47.opt4': 'Coigüe',
    'quiz.q47.explanation': 'El alerce puede vivir más de 3,000 años y es una especie protegida.',

    // Currency History Questions (48-50)
    'quiz.q48.question': '¿Cuál fue la primera moneda independiente de Chile?',
    'quiz.q48.opt1': 'Peso',
    'quiz.q48.opt2': 'Escudo',
    'quiz.q48.opt3': 'Real Español',
    'quiz.q48.opt4': 'Real Chileno',
    'quiz.q48.explanation': 'El real chileno fue la primera moneda independiente de Chile después de la independencia.',

    'quiz.q49.question': '¿Cuándo se introdujo el peso chileno actual?',
    'quiz.q49.opt1': '1975',
    'quiz.q49.opt2': '1960',
    'quiz.q49.opt3': '1980',
    'quiz.q49.opt4': '1990',
    'quiz.q49.explanation': 'El peso chileno actual se introdujo en 1975, reemplazando al escudo.',

    'quiz.q50.question': '¿Cuál es el símbolo del peso chileno?',
    'quiz.q50.opt1': '$',
    'quiz.q50.opt2': 'P',
    'quiz.q50.opt3': 'CH$',
    'quiz.q50.opt4': 'CLP',
    'quiz.q50.explanation': 'El símbolo del peso chileno es $ al igual que otras monedas latinoamericanas.',
  },
  en: {
    // Header
    'header.back': 'Back',
    'header.title': 'History of Chile',
    'header.takeQuiz': 'Take Quiz',

    // Main
    'main.title': 'Discover the History of Chile',
    'main.subtitle': 'Explore the key events, figures, and moments that shaped the Chilean nation from pre-Columbian times to the present.',
    'main.testKnowledge': 'Test Your Knowledge',

    // Tabs
    'tabs.history': 'History',
    'tabs.culture': 'Culture',

    // Sections
    'sections.keyEvents': 'Key Events',
    'sections.keyFigures': 'Key Figures',

    // Quiz
    'quiz.title': 'Chilean History Quiz',
    'quiz.home': 'Home',
    'quiz.questionNumber': 'Question',
    'quiz.of': 'of',
    'quiz.difficulty': 'Difficulty',
    'quiz.easy': 'Easy',
    'quiz.medium': 'Medium',
    'quiz.hard': 'Hard',
    'quiz.previous': 'Previous',
    'quiz.showAnswer': 'Show Answer',
    'quiz.results': 'Results',
    'quiz.completed': 'Quiz Completed!',
    'quiz.scored': 'You scored',
    'quiz.outOf': 'out of',
    'quiz.questions': 'questions',
    'quiz.timeSpent': 'Time',
    'quiz.grade': 'Grade',
    'quiz.excellent': 'Excellent!',
    'quiz.goodJob': 'Good Job!',
    'quiz.notBad': 'Not Bad',
    'quiz.keepStudying': 'Keep Studying',
    'quiz.retryQuiz': 'Retry Quiz',
    'quiz.reviewMistakes': 'Review Mistakes',
    'quiz.nextQuestion': 'Next Question',
    'quiz.finishQuiz': 'Finish Quiz',

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signInDescription': 'Sign in to your account to continue learning Chilean history',
    'auth.signUpDescription': 'Join Chilenizate to track your progress and save your results',
    'auth.fullName': 'Full Name',
    'auth.enterFullName': 'Enter your full name',
    'auth.email': 'Email',
    'auth.enterEmail': 'Enter your email',
    'auth.password': 'Password',
    'auth.enterPassword': 'Enter your password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.pleaseWait': 'Please wait...',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.home': 'Home',

    // Error Bin
    'errorBin.title': 'Error Bin',
    'errorBin.noErrors': 'No Errors Yet!',
    'errorBin.emptyDescription': 'Your error bin is empty. Take the quiz to see questions you answered incorrectly here for review.',
    'errorBin.takeQuiz': 'Take Quiz',
    'errorBin.yourErrorBin': 'Your Error Bin',
    'errorBin.reviewPractice': 'Review and Practice',
    'errorBin.questionsWrong': 'question(s) you answered incorrectly',
    'errorBin.practiceAll': 'Practice All Questions',
    'errorBin.clearAll': 'Clear All',
    'errorBin.practiceMode': 'Practice Mode',
    'errorBin.exitPractice': 'Exit Practice',
    'errorBin.practiceComplete': 'Practice Complete',
    'errorBin.greatJob': 'Great Job!',
    'errorBin.completedSession': 'You have completed your error bin practice session.',
    'errorBin.returnToBin': 'Return to Error Bin',
    'errorBin.takeFullQuiz': 'Take Full Quiz Again',
    'errorBin.previouslyIncorrect': 'This question was previously answered incorrectly. Answer correctly to remove it from your error bin.',
    'errorBin.explanation': 'Explanation:',
    'errorBin.loading': 'Loading error questions...',

    // Quiz Questions - Historical
    'quiz.q1.question': 'Who founded the city of Santiago in 1541?',
    'quiz.q1.opt1': 'Pedro de Valdivia',
    'quiz.q1.opt2': 'Diego de Almagro',
    'quiz.q1.opt3': 'Francisco Pizarro',
    'quiz.q1.opt4': 'Hernán Cortés',
    'quiz.q1.explanation': 'Pedro de Valdivia founded Santiago de la Nueva Extremadura on February 12, 1541.',

    'quiz.q2.question': 'In what year did Chile declare its independence?',
    'quiz.q2.opt1': '1810',
    'quiz.q2.opt2': '1818',
    'quiz.q2.opt3': '1817',
    'quiz.q2.opt4': '1820',
    'quiz.q2.explanation': 'Chile formally declared independence in 1818, although the process began in 1810.',

    'quiz.q3.question': 'What was the decisive battle for Chilean independence?',
    'quiz.q3.opt1': 'Battle of Rancagua',
    'quiz.q3.opt2': 'Battle of Maipú',
    'quiz.q3.opt3': 'Battle of Chacabuco',
    'quiz.q3.opt4': 'Battle of Cancha Rayada',
    'quiz.q3.explanation': 'The Battle of Chacabuco (1817) was decisive in securing Chilean independence.',

    'quiz.q4.question': 'Who was the first president of Chile?',
    'quiz.q4.opt1': 'José Miguel Carrera',
    'quiz.q4.opt2': 'Bernardo O\'Higgins',
    'quiz.q4.opt3': 'Manuel Blanco Encalada',
    'quiz.q4.opt4': 'Ramón Freire',
    'quiz.q4.explanation': 'Bernardo O\'Higgins was the first Supreme Director (equivalent to president) of Chile.',

    'quiz.q5.question': 'Which war significantly expanded Chilean territory?',
    'quiz.q5.opt1': 'War of the Confederation',
    'quiz.q5.opt2': 'War of the Pacific',
    'quiz.q5.opt3': 'Arauco War',
    'quiz.q5.opt4': 'Civil War of 1891',
    'quiz.q5.explanation': 'The War of the Pacific (1879-1884) allowed Chile to gain territory in the north.',

    'quiz.q6.question': 'What was the main export product during the 19th century?',
    'quiz.q6.opt1': 'Copper',
    'quiz.q6.opt2': 'Saltpeter',
    'quiz.q6.opt3': 'Silver',
    'quiz.q6.opt4': 'Wheat',
    'quiz.q6.explanation': 'Saltpeter was the main export product that brought great wealth to Chile.',

    'quiz.q7.question': 'Who was the most famous Mapuche leader in the Spanish resistance?',
    'quiz.q7.opt1': 'Caupolicán',
    'quiz.q7.opt2': 'Lautaro',
    'quiz.q7.opt3': 'Galvarino',
    'quiz.q7.opt4': 'Janequeo',
    'quiz.q7.explanation': 'Lautaro was one of the most prominent Mapuche leaders in the Arauco War.',

    'quiz.q8.question': 'In what year was the current Chilean Constitution promulgated?',
    'quiz.q8.opt1': '1925',
    'quiz.q8.opt2': '1980',
    'quiz.q8.opt3': '1990',
    'quiz.q8.opt4': '2005',
    'quiz.q8.explanation': 'The current Constitution was promulgated in 1980 during the military government.',

    'quiz.q9.question': 'What was Chile\'s first political party?',
    'quiz.q9.opt1': 'Liberal Party',
    'quiz.q9.opt2': 'Conservative Party',
    'quiz.q9.opt3': 'Radical Party',
    'quiz.q9.opt4': 'National Party',
    'quiz.q9.explanation': 'The Liberal Party was one of Chile\'s first formal political parties.',

    'quiz.q10.question': 'Who was president during the Great Depression in Chile?',
    'quiz.q10.opt1': 'Arturo Alessandri',
    'quiz.q10.opt2': 'Carlos Ibáñez del Campo',
    'quiz.q10.opt3': 'Juan Esteban Montero',
    'quiz.q10.opt4': 'Pedro Aguirre Cerda',
    'quiz.q10.explanation': 'Carlos Ibáñez del Campo governed during part of the Great Depression.',

    'quiz.q11.question': 'When did the Arauco War officially end?',
    'quiz.q11.opt1': '1641',
    'quiz.q11.opt2': '1881',
    'quiz.q11.opt3': '1598',
    'quiz.q11.opt4': '1723',
    'quiz.q11.explanation': 'The Arauco War officially ended in 1881 with the pacification of Araucanía.',

    'quiz.q12.question': 'Who was the last president before the 1973 coup?',
    'quiz.q12.opt1': 'Eduardo Frei Montalva',
    'quiz.q12.opt2': 'Salvador Allende',
    'quiz.q12.opt3': 'Jorge Alessandri',
    'quiz.q12.opt4': 'Gabriel González Videla',
    'quiz.q12.explanation': 'Salvador Allende was overthrown in the military coup on September 11, 1973.',

    'quiz.q13.question': 'Which president implemented the most significant agrarian reform?',
    'quiz.q13.opt1': 'Jorge Alessandri',
    'quiz.q13.opt2': 'Eduardo Frei Montalva',
    'quiz.q13.opt3': 'Salvador Allende',
    'quiz.q13.opt4': 'Carlos Ibáñez del Campo',
    'quiz.q13.explanation': 'Eduardo Frei Montalva implemented significant agrarian reform in the 1960s.',

    'quiz.q14.question': 'What was Santiago\'s original name?',
    'quiz.q14.opt1': 'Santiago del Nuevo Extremo',
    'quiz.q14.opt2': 'Santiago de la Nueva Extremadura',
    'quiz.q14.opt3': 'Santiago de Chile',
    'quiz.q14.opt4': 'Santiago de Compostela',
    'quiz.q14.explanation': 'Santiago was originally founded as Santiago de la Nueva Extremadura.',

    'quiz.q15.question': 'Who led the crossing of the Andes alongside San Martín?',
    'quiz.q15.opt1': 'Bernardo O\'Higgins',
    'quiz.q15.opt2': 'José Miguel Carrera',
    'quiz.q15.opt3': 'Manuel Rodríguez',
    'quiz.q15.opt4': 'Ramón Freire',
    'quiz.q15.explanation': 'Bernardo O\'Higgins closely collaborated with San Martín in the crossing of the Andes.',

    'quiz.q16.question': 'In which century did the first German immigrants arrive in Chile?',
    'quiz.q16.opt1': '17th century',
    'quiz.q16.opt2': '19th century',
    'quiz.q16.opt3': '18th century',
    'quiz.q16.opt4': '20th century',
    'quiz.q16.explanation': 'The first German immigrants arrived in Chile in the 19th century.',

    'quiz.q17.question': 'What was Chile\'s first university?',
    'quiz.q17.opt1': 'University of Chile',
    'quiz.q17.opt2': 'Catholic University',
    'quiz.q17.opt3': 'University of Concepción',
    'quiz.q17.opt4': 'University of Valparaíso',
    'quiz.q17.explanation': 'The University of Chile was the first university in the country, founded in 1842.',

    'quiz.q18.question': 'Which Spanish conquistador first explored Chilean territory?',
    'quiz.q18.opt1': 'Diego de Almagro',
    'quiz.q18.opt2': 'Pedro de Valdivia',
    'quiz.q18.opt3': 'Francisco Pizarro',
    'quiz.q18.opt4': 'Vasco Núñez de Balboa',
    'quiz.q18.explanation': 'Diego de Almagro was the first Spaniard to explore Chilean territory in 1536.',

    'quiz.q19.question': 'How many years did the military government last in Chile?',
    'quiz.q19.opt1': '15 years',
    'quiz.q19.opt2': '16 years',
    'quiz.q19.opt3': '18 years',
    'quiz.q19.opt4': '17 years',
    'quiz.q19.explanation': 'The military government lasted 17 years, from 1973 to 1990.',

    'quiz.q20.question': 'Who was the first president after the return to democracy?',
    'quiz.q20.opt1': 'Eduardo Frei Ruiz-Tagle',
    'quiz.q20.opt2': 'Patricio Aylwin',
    'quiz.q20.opt3': 'Ricardo Lagos',
    'quiz.q20.opt4': 'Michelle Bachelet',
    'quiz.q20.explanation': 'Patricio Aylwin was the first democratic president after the military government.',

    'quiz.q21.question': 'In which region is the Atacama Desert located?',
    'quiz.q21.opt1': 'Tarapacá',
    'quiz.q21.opt2': 'Antofagasta',
    'quiz.q21.opt3': 'Atacama',
    'quiz.q21.opt4': 'All of the above',
    'quiz.q21.explanation': 'The Atacama Desert extends across several northern Chilean regions.',

    'quiz.q22.question': 'What is the highest volcano in Chile?',
    'quiz.q22.opt1': 'Osorno Volcano',
    'quiz.q22.opt2': 'Ojos del Salado',
    'quiz.q22.opt3': 'Villarrica Volcano',
    'quiz.q22.opt4': 'Llaima Volcano',
    'quiz.q22.explanation': 'Ojos del Salado is the highest volcano in Chile and the world.',

    'quiz.q23.question': 'What was Chile\'s first capital?',
    'quiz.q23.opt1': 'Valparaíso',
    'quiz.q23.opt2': 'La Serena',
    'quiz.q23.opt3': 'Santiago',
    'quiz.q23.opt4': 'Concepción',
    'quiz.q23.explanation': 'Santiago has been Chile\'s capital since its founding in 1541.',

    'quiz.q24.question': 'Which Chilean president received the Nobel Prize in Literature?',
    'quiz.q24.opt1': 'Gabriel González Videla',
    'quiz.q24.opt2': 'None was president',
    'quiz.q24.opt3': 'Salvador Allende',
    'quiz.q24.opt4': 'Eduardo Frei Montalva',
    'quiz.q24.explanation': 'No Chilean president has received the Nobel Prize in Literature.',

    'quiz.q25.question': 'What is the longest river in Chile?',
    'quiz.q25.opt1': 'Maipo River',
    'quiz.q25.opt2': 'Loa River',
    'quiz.q25.opt3': 'Bío Bío River',
    'quiz.q25.opt4': 'Baker River',
    'quiz.q25.explanation': 'The Loa River is the longest in Chile, with 440 kilometers.',

    'quiz.q26.question': 'When was Valparaíso founded?',
    'quiz.q26.opt1': '1541',
    'quiz.q26.opt2': '1544',
    'quiz.q26.opt3': '1536',
    'quiz.q26.opt4': '1550',
    'quiz.q26.explanation': 'Valparaíso was founded in 1544 by Juan de Saavedra.',

    'quiz.q27.question': 'Which indigenous ethnicity mainly inhabited northern Chile?',
    'quiz.q27.opt1': 'Mapuches',
    'quiz.q27.opt2': 'Atacameños',
    'quiz.q27.opt3': 'Tehuelches',
    'quiz.q27.opt4': 'Onas',
    'quiz.q27.explanation': 'The Atacameños mainly inhabited northern Chile.',

    'quiz.q28.question': 'What was Chile\'s currency before the current peso?',
    'quiz.q28.opt1': 'Real',
    'quiz.q28.opt2': 'Escudo',
    'quiz.q28.opt3': 'Sol',
    'quiz.q28.opt4': 'Condor',
    'quiz.q28.explanation': 'The escudo was Chile\'s currency between 1960 and 1975.',

    'quiz.q29.question': 'Who wrote "La Araucana"?',
    'quiz.q29.opt1': 'Pedro de Oña',
    'quiz.q29.opt2': 'Alonso de Ercilla',
    'quiz.q29.opt3': 'Francisco Núñez de Pineda',
    'quiz.q29.opt4': 'Diego de Rosales',
    'quiz.q29.explanation': 'Alonso de Ercilla wrote the epic poem "La Araucana".',

    'quiz.q30.question': 'In what year did Chile become a member of the UN?',
    'quiz.q30.opt1': '1945',
    'quiz.q30.opt2': '1946',
    'quiz.q30.opt3': '1947',
    'quiz.q30.opt4': '1948',
    'quiz.q30.explanation': 'Chile was a founding member of the UN in 1945.',

    // New Cultural Questions (31-35)
    'quiz.q31.question': 'What does "Bacán" mean in Chilean slang?',
    'quiz.q31.opt1': 'Cool, amazing',
    'quiz.q31.opt2': 'Boring',
    'quiz.q31.opt3': 'Difficult',
    'quiz.q31.opt4': 'Expensive',
    'quiz.q31.explanation': '"Bacán" is used to express that something is cool or amazing.',

    'quiz.q32.question': 'What does the Cueca dance represent?',
    'quiz.q32.opt1': 'A battle',
    'quiz.q32.opt2': 'A harvest',
    'quiz.q32.opt3': 'The courtship between rooster and hen',
    'quiz.q32.opt4': 'A funeral',
    'quiz.q32.explanation': 'The Cueca represents the courtship between a rooster and a hen.',

    'quiz.q33.question': 'What does "Al tiro" mean in Chile?',
    'quiz.q33.opt1': 'Slowly',
    'quiz.q33.opt2': 'Immediately',
    'quiz.q33.opt3': 'Never',
    'quiz.q33.opt4': 'Maybe',
    'quiz.q33.explanation': '"Al tiro" means immediately or right now.',

    'quiz.q34.question': 'Who is La Pincoya in Chilote mythology?',
    'quiz.q34.opt1': 'A mermaid who brings fortune to fishermen',
    'quiz.q34.opt2': 'An evil ghost',
    'quiz.q34.opt3': 'A forest witch',
    'quiz.q34.opt4': 'A wind spirit',
    'quiz.q34.explanation': 'La Pincoya is a mythical mermaid who brings good fortune to fishermen.',

    'quiz.q35.question': 'What food is essential during the Fiestas Patrias?',
    'quiz.q35.opt1': 'Barbecue',
    'quiz.q35.opt2': 'Cazuela',
    'quiz.q35.opt3': 'Empanadas',
    'quiz.q35.opt4': 'Corn pie',
    'quiz.q35.explanation': 'Empanadas are the traditional essential food during the Fiestas Patrias.',

    // Geography Questions (36-40)
    'quiz.q36.question': 'What is the southernmost region of Chile?',
    'quiz.q36.opt1': 'Los Lagos',
    'quiz.q36.opt2': 'Magallanes and Chilean Antarctica',
    'quiz.q36.opt3': 'Aysén',
    'quiz.q36.opt4': 'Los Ríos',
    'quiz.q36.explanation': 'Magallanes and Chilean Antarctica is the southernmost region of Chile.',

    'quiz.q37.question': 'What is the driest desert in the world located in Chile?',
    'quiz.q37.opt1': 'Atacama Desert',
    'quiz.q37.opt2': 'Sahara Desert',
    'quiz.q37.opt3': 'Gobi Desert',
    'quiz.q37.opt4': 'Kalahari Desert',
    'quiz.q37.explanation': 'The Atacama Desert is considered the driest desert in the world.',

    'quiz.q38.question': 'Which are the most famous islands belonging to Chile?',
    'quiz.q38.opt1': 'Galápagos Islands',
    'quiz.q38.opt2': 'Falkland Islands',
    'quiz.q38.opt3': 'Juan Fernández Islands',
    'quiz.q38.opt4': 'Easter Island (Rapa Nui)',
    'quiz.q38.explanation': 'Easter Island is the most famous Chilean island known for its moai statues.',

    'quiz.q39.question': 'How many regions does Chile currently have?',
    'quiz.q39.opt1': '15',
    'quiz.q39.opt2': '16',
    'quiz.q39.opt3': '14',
    'quiz.q39.opt4': '17',
    'quiz.q39.explanation': 'Chile currently has 16 regions.',

    'quiz.q40.question': 'What is the capital of the Valparaíso region?',
    'quiz.q40.opt1': 'Viña del Mar',
    'quiz.q40.opt2': 'San Antonio',
    'quiz.q40.opt3': 'Valparaíso',
    'quiz.q40.opt4': 'Quillota',
    'quiz.q40.explanation': 'Valparaíso is the capital of the Valparaíso region.',

    // Natural Resources Questions (41-43)
    'quiz.q41.question': 'What is Chile\'s world ranking in copper production?',
    'quiz.q41.opt1': 'First',
    'quiz.q41.opt2': 'Second',
    'quiz.q41.opt3': 'Third',
    'quiz.q41.opt4': 'Fourth',
    'quiz.q41.explanation': 'Chile is the world\'s largest copper producer.',

    'quiz.q42.question': 'Where are Chile\'s largest lithium reserves located?',
    'quiz.q42.opt1': 'Atacama Desert',
    'quiz.q42.opt2': 'Salar de Atacama',
    'quiz.q42.opt3': 'Andes Mountains',
    'quiz.q42.opt4': 'Central Valley',
    'quiz.q42.explanation': 'The Salar de Atacama contains Chile\'s largest lithium reserves.',

    'quiz.q43.question': 'Which is one of the internationally recognized wine-producing regions?',
    'quiz.q43.opt1': 'Maipo Valley',
    'quiz.q43.opt2': 'Elqui Valley',
    'quiz.q43.opt3': 'Colchagua Valley',
    'quiz.q43.opt4': 'All of the above',
    'quiz.q43.explanation': 'All these valleys are internationally recognized for their wine production.',

    // National Symbols Questions (44-47)
    'quiz.q44.question': 'What is Chile\'s national animal?',
    'quiz.q44.opt1': 'Huemul',
    'quiz.q44.opt2': 'Condor',
    'quiz.q44.opt3': 'Chinchilla',
    'quiz.q44.opt4': 'Vicuña',
    'quiz.q44.explanation': 'The huemul is Chile\'s national animal and appears on the national coat of arms.',

    'quiz.q45.question': 'What is Chile\'s national bird?',
    'quiz.q45.opt1': 'Huemul',
    'quiz.q45.opt2': 'Condor',
    'quiz.q45.opt3': 'Flamingo',
    'quiz.q45.opt4': 'Eagle',
    'quiz.q45.explanation': 'The Andean condor is Chile\'s national bird.',

    'quiz.q46.question': 'What is Chile\'s national flower?',
    'quiz.q46.opt1': 'Rose',
    'quiz.q46.opt2': 'Carnation',
    'quiz.q46.opt3': 'Copihue',
    'quiz.q46.opt4': 'Lily',
    'quiz.q46.explanation': 'The copihue is Chile\'s national flower.',

    'quiz.q47.question': 'Which long-living tree can live more than 3,000 years in Chile?',
    'quiz.q47.opt1': 'Araucaria',
    'quiz.q47.opt2': 'Alerce',
    'quiz.q47.opt3': 'Oak',
    'quiz.q47.opt4': 'Coigüe',
    'quiz.q47.explanation': 'The alerce can live more than 3,000 years and is a protected species.',

    // Currency History Questions (48-50)
    'quiz.q48.question': 'What was Chile\'s first independent currency?',
    'quiz.q48.opt1': 'Peso',
    'quiz.q48.opt2': 'Escudo',
    'quiz.q48.opt3': 'Spanish Real',
    'quiz.q48.opt4': 'Chilean Real',
    'quiz.q48.explanation': 'The Chilean real was the first independent currency after independence.',

    'quiz.q49.question': 'When was the current Chilean peso introduced?',
    'quiz.q49.opt1': '1975',
    'quiz.q49.opt2': '1960',
    'quiz.q49.opt3': '1980',
    'quiz.q49.opt4': '1990',
    'quiz.q49.explanation': 'The current Chilean peso was introduced in 1975, replacing the escudo.',

    'quiz.q50.question': 'What is the symbol of the Chilean peso?',
    'quiz.q50.opt1': '$',
    'quiz.q50.opt2': 'P',
    'quiz.q50.opt3': 'CH$',
    'quiz.q50.opt4': 'CLP',
    'quiz.q50.explanation': 'The symbol of the Chilean peso is $, like other Latin American currencies.',
  },
  pt: {
    // Header  
    'header.back': 'Voltar',
    'header.title': 'História do Chile',
    'header.takeQuiz': 'Fazer Quiz',

    // Main
    'main.title': 'Descubra a História do Chile',
    'main.subtitle': 'Explore os eventos, personagens e momentos chave que moldaram a nação chilena desde os tempos pré-colombianos até hoje.',
    'main.testKnowledge': 'Teste seus Conhecimentos',

    // Tabs
    'tabs.history': 'História',
    'tabs.culture': 'Cultura',

    // Sections
    'sections.keyEvents': 'Eventos Chave',
    'sections.keyFigures': 'Figuras Importantes',

    // Quiz
    'quiz.title': 'Quiz da História do Chile',
    'quiz.home': 'Início',
    'quiz.questionNumber': 'Pergunta',
    'quiz.of': 'de',
    'quiz.difficulty': 'Dificuldade',
    'quiz.easy': 'Fácil',
    'quiz.medium': 'Médio',
    'quiz.hard': 'Difícil',
    'quiz.previous': 'Anterior',
    'quiz.showAnswer': 'Mostrar Resposta',
    'quiz.results': 'Resultados',
    'quiz.completed': 'Quiz Completo!',
    'quiz.scored': 'Você acertou',
    'quiz.outOf': 'de',
    'quiz.questions': 'perguntas',
    'quiz.timeSpent': 'Tempo',
    'quiz.grade': 'Nota',
    'quiz.excellent': 'Excelente!',
    'quiz.goodJob': 'Bom Trabalho!',
    'quiz.notBad': 'Nada Mal',
    'quiz.keepStudying': 'Continue Estudando',
    'quiz.retryQuiz': 'Refazer Quiz',
    'quiz.reviewMistakes': 'Revisar Erros',
    'quiz.nextQuestion': 'Próxima Pergunta',
    'quiz.finishQuiz': 'Finalizar Quiz',

    // Auth
    'auth.welcomeBack': 'Bem-vindo de Volta',
    'auth.createAccount': 'Criar Conta',
    'auth.signInDescription': 'Faça login para continuar aprendendo a história chilena',
    'auth.signUpDescription': 'Junte-se ao Chilenizate para acompanhar seu progresso e salvar seus resultados',
    'auth.fullName': 'Nome Completo',
    'auth.enterFullName': 'Digite seu nome completo',
    'auth.email': 'Email',
    'auth.enterEmail': 'Digite seu email',
    'auth.password': 'Senha',
    'auth.enterPassword': 'Digite sua senha',
    'auth.signIn': 'Entrar',
    'auth.signUp': 'Registrar',
    'auth.pleaseWait': 'Por favor, aguarde...',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.haveAccount': 'Já tem uma conta?',
    'auth.home': 'Início',

    // Error Bin
    'errorBin.title': 'Caixa de Erros',
    'errorBin.noErrors': 'Sem Erros Ainda!',
    'errorBin.emptyDescription': 'Sua caixa de erros está vazia. Faça o quiz para ver as perguntas que você errou aqui para revisar.',
    'errorBin.takeQuiz': 'Fazer Quiz',
    'errorBin.yourErrorBin': 'Sua Caixa de Erros',
    'errorBin.reviewPractice': 'Revisar e Praticar',
    'errorBin.questionsWrong': 'pergunta(s) que você errou',
    'errorBin.practiceAll': 'Praticar Todas as Perguntas',
    'errorBin.clearAll': 'Limpar Tudo',
    'errorBin.practiceMode': 'Modo de Prática',
    'errorBin.exitPractice': 'Sair da Prática',
    'errorBin.practiceComplete': 'Prática Completa',
    'errorBin.greatJob': 'Ótimo Trabalho!',
    'errorBin.completedSession': 'Você completou sua sessão de prática da caixa de erros.',
    'errorBin.returnToBin': 'Voltar para a Caixa de Erros',
    'errorBin.takeFullQuiz': 'Refazer Quiz Completo',
    'errorBin.previouslyIncorrect': 'Esta pergunta foi respondida incorretamente anteriormente. Responda corretamente para removê-la da sua caixa de erros.',
    'errorBin.explanation': 'Explicação:',
    'errorBin.loading': 'Carregando perguntas de erros...',

    // Quiz Questions - Historical
    'quiz.q1.question': 'Quem fundou a cidade de Santiago em 1541?',
    'quiz.q1.opt1': 'Pedro de Valdivia',
    'quiz.q1.opt2': 'Diego de Almagro',
    'quiz.q1.opt3': 'Francisco Pizarro',
    'quiz.q1.opt4': 'Hernán Cortés',
    'quiz.q1.explanation': 'Pedro de Valdivia fundou Santiago de la Nueva Extremadura em 12 de fevereiro de 1541.',

    'quiz.q2.question': 'Em que ano o Chile declarou sua independência?',
    'quiz.q2.opt1': '1810',
    'quiz.q2.opt2': '1818',
    'quiz.q2.opt3': '1817',
    'quiz.q2.opt4': '1820',
    'quiz.q2.explanation': 'O Chile declarou formalmente sua independência em 1818, embora o processo tenha começado em 1810.',

    'quiz.q3.question': 'Qual foi a batalha decisiva para a independência do Chile?',
    'quiz.q3.opt1': 'Batalha de Rancagua',
    'quiz.q3.opt2': 'Batalha de Maipú',
    'quiz.q3.opt3': 'Batalha de Chacabuco',
    'quiz.q3.opt4': 'Batalha de Cancha Rayada',
    'quiz.q3.explanation': 'A Batalha de Chacabuco (1817) foi decisiva para garantir a independência do Chile.',

    'quiz.q4.question': 'Quem foi o primeiro presidente do Chile?',
    'quiz.q4.opt1': 'José Miguel Carrera',
    'quiz.q4.opt2': 'Bernardo O\'Higgins',
    'quiz.q4.opt3': 'Manuel Blanco Encalada',
    'quiz.q4.opt4': 'Ramón Freire',
    'quiz.q4.explanation': 'Bernardo O\'Higgins foi o primeiro Diretor Supremo (equivalente a presidente) do Chile.',

    'quiz.q5.question': 'Qual guerra expandiu significativamente o território chileno?',
    'quiz.q5.opt1': 'Guerra da Confederação',
    'quiz.q5.opt2': 'Guerra do Pacífico',
    'quiz.q5.opt3': 'Guerra de Arauco',
    'quiz.q5.opt4': 'Guerra Civil de 1891',
    'quiz.q5.explanation': 'A Guerra do Pacífico (1879-1884) permitiu ao Chile ganhar território no norte.',

    'quiz.q6.question': 'Qual era o principal produto de exportação durante o século XIX?',
    'quiz.q6.opt1': 'Cobre',
    'quiz.q6.opt2': 'Salitre',
    'quiz.q6.opt3': 'Prata',
    'quiz.q6.opt4': 'Trigo',
    'quiz.q6.explanation': 'O salitre foi o principal produto de exportação que trouxe grande riqueza ao Chile.',

    'quiz.q7.question': 'Quem foi o líder mapuche mais famoso na resistência espanhola?',
    'quiz.q7.opt1': 'Caupolicán',
    'quiz.q7.opt2': 'Lautaro',
    'quiz.q7.opt3': 'Galvarino',
    'quiz.q7.opt4': 'Janequeo',
    'quiz.q7.explanation': 'Lautaro foi um dos líderes mapuches mais destacados na Guerra de Arauco.',

    'quiz.q8.question': 'Em que ano foi promulgada a atual Constituição do Chile?',
    'quiz.q8.opt1': '1925',
    'quiz.q8.opt2': '1980',
    'quiz.q8.opt3': '1990',
    'quiz.q8.opt4': '2005',
    'quiz.q8.explanation': 'A atual Constituição foi promulgada em 1980 durante o governo militar.',

    'quiz.q9.question': 'Qual foi o primeiro partido político do Chile?',
    'quiz.q9.opt1': 'Partido Liberal',
    'quiz.q9.opt2': 'Partido Conservador',
    'quiz.q9.opt3': 'Partido Radical',
    'quiz.q9.opt4': 'Partido Nacional',
    'quiz.q9.explanation': 'O Partido Liberal foi um dos primeiros partidos políticos formais do Chile.',

    'quiz.q10.question': 'Quem foi presidente durante a Grande Depressão no Chile?',
    'quiz.q10.opt1': 'Arturo Alessandri',
    'quiz.q10.opt2': 'Carlos Ibáñez del Campo',
    'quiz.q10.opt3': 'Juan Esteban Montero',
    'quiz.q10.opt4': 'Pedro Aguirre Cerda',
    'quiz.q10.explanation': 'Carlos Ibáñez del Campo governou durante parte da Grande Depressão.',

    'quiz.q11.question': 'Quando terminou oficialmente a Guerra de Arauco?',
    'quiz.q11.opt1': '1641',
    'quiz.q11.opt2': '1881',
    'quiz.q11.opt3': '1598',
    'quiz.q11.opt4': '1723',
    'quiz.q11.explanation': 'A Guerra de Arauco terminou oficialmente em 1881 com a pacificação da Araucanía.',

    'quiz.q12.question': 'Quem foi o último presidente antes do golpe de 1973?',
    'quiz.q12.opt1': 'Eduardo Frei Montalva',
    'quiz.q12.opt2': 'Salvador Allende',
    'quiz.q12.opt3': 'Jorge Alessandri',
    'quiz.q12.opt4': 'Gabriel González Videla',
    'quiz.q12.explanation': 'Salvador Allende foi derrubado no golpe militar de 11 de setembro de 1973.',

    'quiz.q13.question': 'Qual presidente implementou a reforma agrária mais significativa?',
    'quiz.q13.opt1': 'Jorge Alessandri',
    'quiz.q13.opt2': 'Eduardo Frei Montalva',
    'quiz.q13.opt3': 'Salvador Allende',
    'quiz.q13.opt4': 'Carlos Ibáñez del Campo',
    'quiz.q13.explanation': 'Eduardo Frei Montalva implementou uma reforma agrária significativa nos anos 60.',

    'quiz.q14.question': 'Qual foi o primeiro nome de Santiago?',
    'quiz.q14.opt1': 'Santiago del Nuevo Extremo',
    'quiz.q14.opt2': 'Santiago de la Nueva Extremadura',
    'quiz.q14.opt3': 'Santiago de Chile',
    'quiz.q14.opt4': 'Santiago de Compostela',
    'quiz.q14.explanation': 'Santiago foi originalmente fundada como Santiago de la Nueva Extremadura.',

    'quiz.q15.question': 'Quem liderou a travessia dos Andes junto com San Martín?',
    'quiz.q15.opt1': 'Bernardo O\'Higgins',
    'quiz.q15.opt2': 'José Miguel Carrera',
    'quiz.q15.opt3': 'Manuel Rodríguez',
    'quiz.q15.opt4': 'Ramón Freire',
    'quiz.q15.explanation': 'Bernardo O\'Higgins colaborou estreitamente com San Martín na travessia dos Andes.',

    'quiz.q16.question': 'Em que século chegaram os primeiros imigrantes alemães ao Chile?',
    'quiz.q16.opt1': 'Século XVII',
    'quiz.q16.opt2': 'Século XIX',
    'quiz.q16.opt3': 'Século XVIII',
    'quiz.q16.opt4': 'Século XX',
    'quiz.q16.explanation': 'Os primeiros imigrantes alemães chegaram ao Chile no século XIX.',

    'quiz.q17.question': 'Qual foi a primeira universidade do Chile?',
    'quiz.q17.opt1': 'Universidade do Chile',
    'quiz.q17.opt2': 'Universidade Católica',
    'quiz.q17.opt3': 'Universidade de Concepción',
    'quiz.q17.opt4': 'Universidade de Valparaíso',
    'quiz.q17.explanation': 'A Universidade do Chile foi a primeira universidade do país, fundada em 1842.',

    'quiz.q18.question': 'Qual conquistador espanhol explorou pela primeira vez o território chileno?',
    'quiz.q18.opt1': 'Diego de Almagro',
    'quiz.q18.opt2': 'Pedro de Valdivia',
    'quiz.q18.opt3': 'Francisco Pizarro',
    'quiz.q18.opt4': 'Vasco Núñez de Balboa',
    'quiz.q18.explanation': 'Diego de Almagro foi o primeiro espanhol a explorar o território chileno em 1536.',

    'quiz.q19.question': 'Quantos anos durou o governo militar no Chile?',
    'quiz.q19.opt1': '15 anos',
    'quiz.q19.opt2': '16 anos',
    'quiz.q19.opt3': '18 anos',
    'quiz.q19.opt4': '17 anos',
    'quiz.q19.explanation': 'O governo militar durou 17 anos, de 1973 a 1990.',

    'quiz.q20.question': 'Quem foi o primeiro presidente após o retorno à democracia?',
    'quiz.q20.opt1': 'Eduardo Frei Ruiz-Tagle',
    'quiz.q20.opt2': 'Patricio Aylwin',
    'quiz.q20.opt3': 'Ricardo Lagos',
    'quiz.q20.opt4': 'Michelle Bachelet',
    'quiz.q20.explanation': 'Patricio Aylwin foi o primeiro presidente democrático após o governo militar.',

    'quiz.q21.question': 'Em qual região está localizado o Deserto do Atacama?',
    'quiz.q21.opt1': 'Tarapacá',
    'quiz.q21.opt2': 'Antofagasta',
    'quiz.q21.opt3': 'Atacama',
    'quiz.q21.opt4': 'Todas as anteriores',
    'quiz.q21.explanation': 'O Deserto do Atacama se estende por várias regiões do norte do Chile.',

    'quiz.q22.question': 'Qual é o vulcão mais alto do Chile?',
    'quiz.q22.opt1': 'Vulcão Osorno',
    'quiz.q22.opt2': 'Ojos del Salado',
    'quiz.q22.opt3': 'Vulcão Villarrica',
    'quiz.q22.opt4': 'Vulcão Llaima',
    'quiz.q22.explanation': 'Ojos del Salado é o vulcão mais alto do Chile e do mundo.',

    'quiz.q23.question': 'Qual foi a primeira capital do Chile?',
    'quiz.q23.opt1': 'Valparaíso',
    'quiz.q23.opt2': 'La Serena',
    'quiz.q23.opt3': 'Santiago',
    'quiz.q23.opt4': 'Concepción',
    'quiz.q23.explanation': 'Santiago é a capital do Chile desde sua fundação em 1541.',

    'quiz.q24.question': 'Qual presidente chileno recebeu o Prêmio Nobel de Literatura?',
    'quiz.q24.opt1': 'Gabriel González Videla',
    'quiz.q24.opt2': 'Nenhum foi presidente',
    'quiz.q24.opt3': 'Salvador Allende',
    'quiz.q24.opt4': 'Eduardo Frei Montalva',
    'quiz.q24.explanation': 'Nenhum presidente chileno recebeu o Prêmio Nobel de Literatura.',

    'quiz.q25.question': 'Qual é o rio mais longo do Chile?',
    'quiz.q25.opt1': 'Rio Maipo',
    'quiz.q25.opt2': 'Rio Loa',
    'quiz.q25.opt3': 'Rio Bío Bío',
    'quiz.q25.opt4': 'Rio Baker',
    'quiz.q25.explanation': 'O Rio Loa é o mais longo do Chile, com 440 quilômetros.',

    'quiz.q26.question': 'Quando foi fundada Valparaíso?',
    'quiz.q26.opt1': '1541',
    'quiz.q26.opt2': '1544',
    'quiz.q26.opt3': '1536',
    'quiz.q26.opt4': '1550',
    'quiz.q26.explanation': 'Valparaíso foi fundada em 1544 por Juan de Saavedra.',

    'quiz.q27.question': 'Qual etnia indígena habitava principalmente o norte do Chile?',
    'quiz.q27.opt1': 'Mapuches',
    'quiz.q27.opt2': 'Atacameños',
    'quiz.q27.opt3': 'Tehuelches',
    'quiz.q27.opt4': 'Onas',
    'quiz.q27.explanation': 'Os atacameños habitavam principalmente o norte do Chile.',

    'quiz.q28.question': 'Qual foi a moeda chilena antes do peso atual?',
    'quiz.q28.opt1': 'Real',
    'quiz.q28.opt2': 'Escudo',
    'quiz.q28.opt3': 'Sol',
    'quiz.q28.opt4': 'Condor',
    'quiz.q28.explanation': 'O escudo foi a moeda chilena entre 1960 e 1975.',

    'quiz.q29.question': 'Quem escreveu "La Araucana"?',
    'quiz.q29.opt1': 'Pedro de Oña',
    'quiz.q29.opt2': 'Alonso de Ercilla',
    'quiz.q29.opt3': 'Francisco Núñez de Pineda',
    'quiz.q29.opt4': 'Diego de Rosales',
    'quiz.q29.explanation': 'Alonso de Ercilla escreveu o poema épico "La Araucana".',

    'quiz.q30.question': 'Em que ano o Chile se tornou membro da ONU?',
    'quiz.q30.opt1': '1945',
    'quiz.q30.opt2': '1946',
    'quiz.q30.opt3': '1947',
    'quiz.q30.opt4': '1948',
    'quiz.q30.explanation': 'O Chile foi um dos membros fundadores da ONU em 1945.',

    // New Cultural Questions (31-35)
    'quiz.q31.question': 'Qual é o significado de "Bacán" no chileno?',
    'quiz.q31.opt1': 'Legal, incrível',
    'quiz.q31.opt2': 'Chato',
    'quiz.q31.opt3': 'Difícil',
    'quiz.q31.opt4': 'Caro',
    'quiz.q31.explanation': '"Bacán" é usado para expressar que algo é legal ou incrível.',

    'quiz.q32.question': 'O que representa a dança da Cueca?',
    'quiz.q32.opt1': 'Uma batalha',
    'quiz.q32.opt2': 'Uma colheita',
    'quiz.q32.opt3': 'O cortejo entre galo e galinha',
    'quiz.q32.opt4': 'Um funeral',
    'quiz.q32.explanation': 'A Cueca representa o cortejo amoroso entre um galo e uma galinha.',

    'quiz.q33.question': 'O que significa "Al tiro" no Chile?',
    'quiz.q33.opt1': 'Devagar',
    'quiz.q33.opt2': 'Imediatamente',
    'quiz.q33.opt3': 'Nunca',
    'quiz.q33.opt4': 'Talvez',
    'quiz.q33.explanation': '"Al tiro" significa imediatamente ou agora mesmo.',

    'quiz.q34.question': 'Quem é La Pincoya na mitologia chilota?',
    'quiz.q34.opt1': 'Uma sereia que traz sorte aos pescadores',
    'quiz.q34.opt2': 'Um fantasma malévolo',
    'quiz.q34.opt3': 'Uma bruxa da floresta',
    'quiz.q34.opt4': 'Um espírito do vento',
    'quiz.q34.explanation': 'La Pincoya é uma sereia mítica que traz boa sorte aos pescadores.',

    'quiz.q35.question': 'Qual comida é essencial durante as Fiestas Patrias?',
    'quiz.q35.opt1': 'Churrasco',
    'quiz.q35.opt2': 'Cazuela',
    'quiz.q35.opt3': 'Empanadas',
    'quiz.q35.opt4': 'Pastel de choclo',
    'quiz.q35.explanation': 'As empanadas são a comida tradicional essencial durante as Fiestas Patrias.',

    // Geography Questions (36-40)
    'quiz.q36.question': 'Qual é a região mais austral do Chile?',
    'quiz.q36.opt1': 'Los Lagos',
    'quiz.q36.opt2': 'Magallanes e Antártica Chilena',
    'quiz.q36.opt3': 'Aysén',
    'quiz.q36.opt4': 'Los Ríos',
    'quiz.q36.explanation': 'Magallanes e Antártica Chilena é a região mais austral do Chile.',

    'quiz.q37.question': 'Qual é o deserto mais árido do mundo localizado no Chile?',
    'quiz.q37.opt1': 'Deserto do Atacama',
    'quiz.q37.opt2': 'Deserto do Saara',
    'quiz.q37.opt3': 'Deserto de Gobi',
    'quiz.q37.opt4': 'Deserto do Kalahari',
    'quiz.q37.explanation': 'O Deserto do Atacama é considerado o mais árido do mundo.',

    'quiz.q38.question': 'Quais são as ilhas mais famosas pertencentes ao Chile?',
    'quiz.q38.opt1': 'Ilhas Galápagos',
    'quiz.q38.opt2': 'Ilhas Malvinas',
    'quiz.q38.opt3': 'Ilhas Juan Fernández',
    'quiz.q38.opt4': 'Ilha de Páscoa (Rapa Nui)',
    'quiz.q38.explanation': 'A Ilha de Páscoa é a mais famosa das ilhas chilenas por seus moais.',

    'quiz.q39.question': 'Quantas regiões o Chile tem atualmente?',
    'quiz.q39.opt1': '15',
    'quiz.q39.opt2': '16',
    'quiz.q39.opt3': '14',
    'quiz.q39.opt4': '17',
    'quiz.q39.explanation': 'O Chile tem atualmente 16 regiões.',

    'quiz.q40.question': 'Qual é a capital da região de Valparaíso?',
    'quiz.q40.opt1': 'Viña del Mar',
    'quiz.q40.opt2': 'San Antonio',
    'quiz.q40.opt3': 'Valparaíso',
    'quiz.q40.opt4': 'Quillota',
    'quiz.q40.explanation': 'Valparaíso é a capital da região de Valparaíso.',

    // Natural Resources Questions (41-43)
    'quiz.q41.question': 'Qual é a posição mundial do Chile na produção de cobre?',
    'quiz.q41.opt1': 'Primeira',
    'quiz.q41.opt2': 'Segunda',
    'quiz.q41.opt3': 'Terceira',
    'quiz.q41.opt4': 'Quarta',
    'quiz.q41.explanation': 'O Chile é o maior produtor mundial de cobre.',

    'quiz.q42.question': 'Onde estão as maiores reservas de lítio do Chile?',
    'quiz.q42.opt1': 'Deserto do Atacama',
    'quiz.q42.opt2': 'Salar de Atacama',
    'quiz.q42.opt3': 'Cordilheira dos Andes',
    'quiz.q42.opt4': 'Vale Central',
    'quiz.q42.explanation': 'O Salar de Atacama contém as maiores reservas de lítio do Chile.',

    'quiz.q43.question': 'Qual é uma das indústrias vinícolas mais reconhecidas internacionalmente?',
    'quiz.q43.opt1': 'Vale do Maipo',
    'quiz.q43.opt2': 'Vale do Elqui',
    'quiz.q43.opt3': 'Vale de Colchagua',
    'quiz.q43.opt4': 'Todas as anteriores',
    'quiz.q43.explanation': 'Todos esses vales são reconhecidos mundialmente pela produção vinícola.',

    // National Symbols Questions (44-47)
    'quiz.q44.question': 'Qual é o animal nacional do Chile?',
    'quiz.q44.opt1': 'Huemul',
    'quiz.q44.opt2': 'Cóndor',
    'quiz.q44.opt3': 'Chinchilla',
    'quiz.q44.opt4': 'Vicuña',
    'quiz.q44.explanation': 'O huemul é o animal nacional do Chile e aparece no brasão nacional.',

    'quiz.q45.question': 'Qual é a ave nacional do Chile?',
    'quiz.q45.opt1': 'Huemul',
    'quiz.q45.opt2': 'Cóndor',
    'quiz.q45.opt3': 'Flamingo',
    'quiz.q45.opt4': 'Águia',
    'quiz.q45.explanation': 'O cóndor andino é a ave nacional do Chile.',

    'quiz.q46.question': 'Qual é a flor nacional do Chile?',
    'quiz.q46.opt1': 'Rosa',
    'quiz.q46.opt2': 'Cravo',
    'quiz.q46.opt3': 'Copihue',
    'quiz.q46.opt4': 'Lírio',
    'quiz.q46.explanation': 'O copihue é a flor nacional do Chile.',

    'quiz.q47.question': 'Qual árvore longeva pode viver mais de 3.000 anos no Chile?',
    'quiz.q47.opt1': 'Araucária',
    'quiz.q47.opt2': 'Alerce',
    'quiz.q47.opt3': 'Carvalho',
    'quiz.q47.opt4': 'Coigüe',
    'quiz.q47.explanation': 'O alerce pode viver mais de 3.000 anos e é uma espécie protegida.',

    // Currency History Questions (48-50)
    'quiz.q48.question': 'Qual foi a primeira moeda independente do Chile?',
    'quiz.q48.opt1': 'Peso',
    'quiz.q48.opt2': 'Escudo',
    'quiz.q48.opt3': 'Real Espanhol',
    'quiz.q48.opt4': 'Real Chileno',
    'quiz.q48.explanation': 'O real chileno foi a primeira moeda independente do Chile após a independência.',

    'quiz.q49.question': 'Quando foi introduzido o peso chileno atual?',
    'quiz.q49.opt1': '1975',
    'quiz.q49.opt2': '1960',
    'quiz.q49.opt3': '1980',
    'quiz.q49.opt4': '1990',
    'quiz.q49.explanation': 'O peso chileno atual foi introduzido em 1975, substituindo o escudo.',

    'quiz.q50.question': 'Qual é o símbolo do peso chileno?',
    'quiz.q50.opt1': '$',
    'quiz.q50.opt2': 'P',
    'quiz.q50.opt3': 'CH$',
    'quiz.q50.opt4': 'CLP',
    'quiz.q50.explanation': 'O símbolo do peso chileno é $ como outras moedas latino-americanas.',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es'); // Default to Spanish

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
