// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fopblvwhfyyzayvcgrti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcGJsdndoZnl5emF5dmNncnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDM4MTMsImV4cCI6MjA2NjYxOTgxM30.GJ-qTsEAA3wJgZr9UMyA2v85q3MEYvBhYA11g0gdj6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);